### PR TITLE
Why? Users should be able to reset their password if they forget it. …

### PR DESCRIPTION
**Pull request by ydaniju**
…How?

Create a forgot password page to enter email where info on how to reset
password is sent.

### CODE REVIEW

**Comment by makinwab** [comment]
A forgot password link is not available in the sign in page. How do we visit that page?

**Comment by makinwab** [comment]
What is the `cancel` link in the forgot password page meant for? Nothing happens when its clicked on.

**Comment by makinwab** [comment]
You changed the color for Sign In and Sign Up links in _Got an account? Sign In_ and _If you do not have an account, please Sign Up_ respectively? It should still take the old link color. This also goes for the _Forgot password_ link.

**Comment by ydaniju** [comment]
Yea. Done!. Listening to too many advisers could cause confusion. : )

On Mon, Dec 14, 2015 at 5:19 PM, Makinwa Olubukola <notifications@github.com

**Pull request merged**
