### PR TITLE
Fix suggestions raised on Category PR [Finishes #113810451]

### PR DESCRIPTION
**Pull request by 0duaht**
https://www.pivotaltracker.com/story/show/113810451

### CODE REVIEW

**Comment by sofiengwin** [comment]
:+1:

**Comment by ChigboIO** [comment]
:+1:

**Comment by oluosiname** [comment]
:+1:

**Comment by ydaniju** [comment]
:+1:

On Tue, Feb 16, 2016 at 1:42 PM, Olumuyiwa Osiname <notifications@github.com

> wrote:
> 
> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/getmyshop/pull/49#issuecomment-184667221.

## 

_Best Regards,_

_Yusuf Daniju /_\* Andela.com
http://andela.com/?utm_source=andela&utm_medium=email&utm_campaign=signature *
_Software Developer / *_+234.807.266.7248 <+234.807.266.7248>*\* / @Andela
http://bit.ly/andelatwitter*

*"The startup that's harder to get into than Harvard" - *CNN
http://snip.ly/HfId
See what The Wall Street Journal http://snip.ly/u9AI has to say.

**Comment by makinwab** [comment]
@andela-toduah do we need to have the pagination at the top and bottom?

**Comment by 0duaht** [comment]
@andela-bmakinwa, UX-wise, it's needed. I'd rather not have to scroll up from the bottom of the page if I want to see the next list of products, or vice-versa from the top of the page.

**Pull request merged**
