### PR TITLE
Designed search box

### PR DESCRIPTION
**Pull request by sofiengwin**
Why?
Given that I am a user, I should be able to search for products using the search box available at the top of each page. The search box takes the user to the search result page.

How?
Designing a search box which is available on every page in the site. The search
box is hidden by default, it is activated by clicking on the search icon in the nav bar.

https://www.pivotaltracker.com/story/show/113281059

[finishes #113281059]

final commit

Test

### CODE REVIEW

**Comment by 0duaht** [comment]
Hi @andela-gogbara, Nice work on the search-box transition.
The search icon and text-field seem not to be aligned vertically with the remaining items in the nav-bar.
The input field looks to be a bit too big though, and the green background seems off. 
A white input field with a non-white border might look better. What do you think?

**Comment by sofiengwin** [comment]
Thanks for the comment @andela-toduah it looks better with the changes you suggested. I appreciate your help in  making it better.

**Comment by makinwab** [comment]
@andela-gogbara the search input field should not have all those borders around. It could simply have only the border bottom transition out/in.

Also, the source of transition is quite far from the search button which should not be so. The border-bottom of the search field should be at the same level as the bottom of the search icon.

Let's also reduce the size and weight of the search icon a bit. It could have the same weight as the nav text if possible.

**Comment by sofiengwin** [comment]
@andela-bmakinwa I made the changes you recommended. Nice one, the design looks much better.

**Pull request merged**
