### PR TITLE
Redesign category dropdown

### PR DESCRIPTION
**Pull request by ydaniju**
Why?

The old category dropdown was just a placeholder

How?

Make the display a giant one with appealing look

https://www.pivotaltracker.com/story/show/113280925
[Finishes #113280925]

### CODE REVIEW

**Comment by ChigboIO** [comment]
I'm thinking if there is another way we could handle the multiple-line entry in the dropdown. What does everyone think about giving it a horizontal scroll when it overflows? Maintaining just a single line. :question: :question: :question:

**Comment by 0duaht** [comment]
@andela-echigbo Horizontal scrolls almost never end well most times. Here are a few articles explaining why:
http://www.experienceux.co.uk/ux-blog/2011/12/12/a-ux-perspective-on-horizontal-scrolling/
https://www.nngroup.com/articles/horizontal-scrolling/

However, let's all give our opinions on this.

**Comment by 0duaht** [comment]
Nice job @andela-ydaniju. :+1:

**Comment by ChigboIO** [comment]
That makes a lot of sense @andela-toduah. Giving that most computer mouse does not easily support the horizontal scrolling… and we want to be there for all. I am beginning to forget about `non-mac` computers. :smile:

**Comment by sofiengwin** [comment]
Nice work @andela-ydaniju :+1:

**Pull request merged**
