### PR TITLE
Oauth Authentication for Users [Finishes #110060596]

### PR DESCRIPTION
**Pull request by 0duaht**
Why?

A user could want to sign up using facebook, twitter or google.

How?

Implement policies for all three social media platform by:
a. Separating regular user from oauth user
b. Opening accounts on all three social media platforms
c. Signing user into sessions once the implementation is properly done

https://www.pivotaltracker.com/story/show/110060596

### CODE REVIEW

**Comment by makinwab** [comment]
@andela-toduah and @danijuyusuf there are issues with Google and Facebook authentication. We should fix that.

**Comment by andela-oosiname** [comment]
The facebook and google authentications are giving errors, please look into that.

**Comment by ChigboIO** [comment]
:+1: on the feature
Twitter works just fine.
However, I was neither able to login with facebook nor with Google.
How can we fix that?

**Comment by ydaniju** [comment]
Oh! We found the bug. I used Time.at.utc without arguments.

On Tue, Jan 19, 2016 at 12:36 PM, Emmanuel Chigbo notifications@github.com
wrote:

> [image: :+1:] on the feature
> Twitter works just fine.
> However, I was neither able to login with facebook nor with Google.
> How can we fix that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/getmyshop/pull/31#issuecomment-172824843.

## 

_Best Regards,_

_Yusuf Daniju /_\* Andela.com
http://andela.com/?utm_source=andela&utm_medium=email&utm_campaign=signature *
_Software Developer / *_+234.807.266.7248 <+234.807.266.7248>*\* / @Andela
http://bit.ly/andelatwitter*

*"The startup that's harder to get into than Harvard" - *CNN
http://snip.ly/HfId
See what The Wall Street Journal http://snip.ly/u9AI has to say.

**Comment by 0duaht** [comment]
Problems fixed. Thanks all, for spotting that.

**Comment by ChigboIO** [comment]
:100: @andela-toduah and @andela-ydaniju

**Comment by oluosiname** [comment]
Nice one @andela-toduah and @andela-ydaniju

**Pull request merged**
