### PR TITLE
Add circle.yml file to project

### PR DESCRIPTION
**Pull request by ydaniju**
Why?
Test don't run yet before deploying to heroku

How?
Specify ruby version and rake spec to file

https://www.pivotaltracker.com/story/show/111969123
[Finishes #111969123]

### CODE REVIEW

**Comment by ChigboIO** [comment]
:+1:

**Comment by ChigboIO** [comment]
@andela-ydaniju: You should rebase and re-push this branch in the just-merged PR

**Comment by codesword** [comment]
The name of the config file should be `circle.yml` not `.circle.yml`. Check out [this](https://circleci.com/docs/configuration) link.
cc @andela-ydaniju

**Comment by ydaniju** [comment]
Thanks for the info. I'm on it now.

On Thu, Jan 21, 2016 at 9:29 AM, Ikem Okonkwo notifications@github.com
wrote:

> The name of the config file should be circle.yml not .circle.yml. Check
> out (https://circleci.com/docs/configuration)[this] link.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/getmyshop/pull/32#issuecomment-173495106.

## 

_Best Regards,_

_Yusuf Daniju /_\* Andela.com
http://andela.com/?utm_source=andela&utm_medium=email&utm_campaign=signature *
_Software Developer / *_+234.807.266.7248 <+234.807.266.7248>*\* / @Andela
http://bit.ly/andelatwitter*

*"The startup that's harder to get into than Harvard" - *CNN
http://snip.ly/HfId
See what The Wall Street Journal http://snip.ly/u9AI has to say.

**Pull request merged**
