### PR TITLE
Designed the 'Product Description' page.

### PR DESCRIPTION
**Pull request by ChigboIO**
Why?
When a product is click, we need a page where all the details of the
specific product is displayed. From this page, shop cusotomers can decide
to buy the product, add it to their wishlist and see other related
products.

How?
Create a Products controller,
Create the 'show product' view,
Create the route that points to this page
Create the scss stiesheet file for this view
Create a js file that initializes some scripts is this page.

Completed 'Design Product Description Page':
https://www.pivotaltracker.com/story/show/108000136
finished [#108000136]

### CODE REVIEW

**Comment by ydaniju** [comment]
Why do I see 231 violations from hound? Perhaps you should fix scss violations coming from your end leaving out that of landing page.

**Comment by 0duaht** [comment]
There are a lot of scss violations in the landing.scss and products.scss files. Any ideas about fixing them, and merging without conflicts?

**Comment by ydaniju** [comment]
Yeah Tobi. I'm handling them.

**Comment by 0duaht** [comment]
Nice. Well done.

**Comment by ChigboIO** [comment]
I guess what we should do is create a `chore` branches out of master solve those issues, push and create pull request for them. @andela-toduah does for `landing.scss` while I do for `products.scss`

**Comment by ydaniju** [comment]
Good. The nesting of scss masters and conflicting of css rules between
views is causing havoc.

**Pull request merged**
